#Where should player spawn upon joining the server while no game is active
lobby-spawn-location:
  x: -15.7
  y: -38
  z: 8.5
  yaw: -90
  pitch: 0

#Where should the player teleport upon failing the parkour
lobby-parkour-location:
  x: 23.5
  y: -38
  z: 9.5
  yaw: -154
  pitch: -4.5

#Should be a list of locations of lower blocks of doorways.
lobby-start-doors:
  1:
    x: 8
    y: -38
    z: 5
  2:
    x: 11
    y: -38
    z: 8
  3:
    x: 8
    y: -38
    z: 11
  4:
    x: 5
    y: -38
    z: 8

#percentage of players that need to be ready for the countdown to start (0-1)
start-percentage: 0.6

#duration of start-timer in seconds
start-timer-duration: 90

#Minimum number of players needed to start the game:
min-num-of-players: 1

#Duration of sheep morph in seconds
lobby-sheep-morph-duration: 10

#What size should the player scale to when morphed into a mob. If a mob is not listed here (or spelled incorrectly), 1 will be used
disguise-scales:
  sheep: 0.5
  wither_skeleton: 1.25