name: Monstermaze
version: 1.0.0
main: tinesone.monstermaze.MonstermazePlugin
description: PVP gamemode in a maze
author: tinesone
api-version: '1.21.11'
default-permission: op

commands:
  generateMaze:
    description: Generate a maze. Made for testing purposes